version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      
      - run:
          name: Restore, Test and Lint
          command: |
            cd .
            pwd
            ls
            python3 -m venv venv
            . ./venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            export PYTHONPATH=$(pwd)
            pytest
            pip install pylint
            pylint -j 8 --recursive=y ./lib/ clock.py
