version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      
      - run:
          name: Restore, Test and Lint
          command: |
            python3 -m venv venv
            . ./venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            pytest
            pip install pylint
            pylint *.py